### ISSUE TITLE
Climb Blocks

### ISSUE THREAD

**Issue by iGabyTM** [A5H73Y/Carz#15] opened 2018-09-28 11:58 UTC
Adding "OBSIDIAN" to the list, make the car float. 
My suggestion is just to make the car go on top of that block and stay these, not fly around, because atm you can't make something like this ![https://cdn.discordapp.com/attachments/321252016875634688/495201059753558027/unknown.png](https://cdn.discordapp.com/attachments/321252016875634688/495201059753558027/unknown.png)
And add data support for climb blocks (STONE_SLAB:4 - Nether Slabs)

**Comment by A5H73Y** [comment] 2018-09-28 13:12
The whole point of climb blocks is that they are literally made for climbing, that's why you'd dedicate a whole material for it. An example could be SPONGE or something, which you could place at the beginning of that ramp to help you climb up them.
Also data is super bad and completely dropped support in 1.13, so if you updated to 1.13 you could just use the new Material types.

**Comment by A5H73Y** [comment] 2019-09-26 08:33
Duplicate of #6

**Closed by A5H73Y** 2019-09-26 08:33 UTC
